name: Rust

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 */6 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run
      env:
        API_KEY: ${{ secrets.API_KEY }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: cargo run --verbose
