name: Rust

on:
  push:
    paths:
     - src/main.rs
     - .github/workflows/generate.yml
  schedule:
    - cron: "0 */6 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run
      env:
        API_KEY: ${{ secrets.API_KEY }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: cargo run --verbose
    - name: Commit and push new README.md to the repo
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: "main"
